#!/usr/bin/env bash
set -euo pipefail

# =========================
# oxStack Install Script
# Links skills, agents, and guidelines to AI tool config directories.
# =========================

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
SKILLS_DIR="$SCRIPT_DIR/skills"
AGENTS_DIR="$SCRIPT_DIR/agents"
GUIDELINES_DIR="$SCRIPT_DIR/guidelines"
MCP_DIR="$SCRIPT_DIR/mcp"
ENV_FILE="$SCRIPT_DIR/.env"

CLAUDE_SKILLS="$HOME/.claude/skills"
AGENTS_SKILLS="$HOME/.agents/skills"
CLAUDE_AGENTS="$HOME/.claude/agents"
CLAUDE_SETTINGS="$HOME/.claude/settings.json"
CODEX_DIR="$HOME/.codex"
CODEX_CONFIG="$HOME/.codex/config.toml"
OPENCODE_DIR="$HOME/.opencode"

GENERATED_HEADER="<!-- Generated by oxStack/install.sh — edit files in the oxStack repo instead -->"

# ---- Colors ----
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
RED='\033[0;31m'
NC='\033[0m'

info()  { echo -e "${GREEN}+${NC} $1"; }
warn()  { echo -e "${YELLOW}!${NC} $1"; }
error() { echo -e "${RED}x${NC} $1"; }

# ---- Backup a real file/dir before replacing ----
backup_if_real() {
  local target="$1"
  if [[ -e "$target" && ! -L "$target" ]]; then
    local bak="${target}.bak"
    warn "Backing up $target → $bak"
    mv "$target" "$bak"
  fi
}

# ---- Remove a symlink only if it points to our repo ----
remove_our_link() {
  local target="$1"
  if [[ -L "$target" ]]; then
    local link_target
    link_target="$(readlink -f "$target" 2>/dev/null || readlink "$target")"
    if [[ "$link_target" == "$SCRIPT_DIR"* ]]; then
      rm "$target"
      return 0
    fi
  fi
  return 1
}

# ---- INSTALL ----
do_install() {
  echo "Installing oxStack..."
  echo ""

  # --- Skills → ~/.claude/skills/ and ~/.agents/skills/ ---
  mkdir -p "$CLAUDE_SKILLS" "$AGENTS_SKILLS"

  for skill_dir in "$SKILLS_DIR"/*/; do
    [[ -d "$skill_dir" ]] || continue
    local name
    name="$(basename "$skill_dir")"

    # Claude skills target
    local claude_target="$CLAUDE_SKILLS/$name"
    if [[ -L "$claude_target" ]]; then
      rm "$claude_target"
    else
      backup_if_real "$claude_target"
    fi
    ln -sfn "$skill_dir" "$claude_target"
    info "Skill $name → $claude_target"

    # Agents skills target
    local agents_target="$AGENTS_SKILLS/$name"
    if [[ -L "$agents_target" ]]; then
      rm "$agents_target"
    else
      backup_if_real "$agents_target"
    fi
    ln -sfn "$skill_dir" "$agents_target"
    info "Skill $name → $agents_target"
  done

  echo ""

  # --- Agents → ~/.claude/agents/ ---
  mkdir -p "$CLAUDE_AGENTS"

  for agent_file in "$AGENTS_DIR"/*.md; do
    [[ -f "$agent_file" ]] || continue
    local name
    name="$(basename "$agent_file")"

    local target="$CLAUDE_AGENTS/$name"
    if [[ -L "$target" ]]; then
      rm "$target"
    else
      backup_if_real "$target"
    fi
    ln -sf "$agent_file" "$target"
    info "Agent $name → $target"
  done

  echo ""

  # --- Guidelines → Codex AGENTS.md ---
  if [[ -d "$CODEX_DIR" ]]; then
    local codex_agents="$CODEX_DIR/AGENTS.md"
    backup_if_real "$codex_agents"
    {
      echo "$GENERATED_HEADER"
      echo ""
      cat "$GUIDELINES_DIR/base-guidelines.md"
      echo ""
      cat "$GUIDELINES_DIR/agent-appendix.md"
    } > "$codex_agents"
    info "Generated $codex_agents"
  else
    warn "Skipping Codex ($CODEX_DIR not found)"
  fi

  # --- Guidelines → OpenCode AGENTS.md ---
  if [[ -d "$OPENCODE_DIR" ]]; then
    local opencode_agents="$OPENCODE_DIR/AGENTS.md"
    backup_if_real "$opencode_agents"
    {
      echo "$GENERATED_HEADER"
      echo ""
      cat "$GUIDELINES_DIR/base-guidelines.md"
      echo ""
      cat "$GUIDELINES_DIR/opencode-extra.md"
      echo ""
      cat "$GUIDELINES_DIR/agent-appendix.md"
    } > "$opencode_agents"
    info "Generated $opencode_agents"
  else
    warn "Skipping OpenCode ($OPENCODE_DIR not found)"
  fi

  # --- MCP servers ---
  install_mcp

  echo ""

  # --- gstack + agent-browser ---
  "$SCRIPT_DIR/gstack-ab/install-gstack.sh"

  echo ""
  info "Done. All skills, agents, guidelines, and MCP servers installed."
}

# ---- Load .env ----
load_env() {
  if [[ -f "$ENV_FILE" ]]; then
    set -a
    source "$ENV_FILE"
    set +a
  else
    warn "No .env file found — copy .env.example to .env and fill in values"
    warn "MCP servers requiring env vars (e.g. AWS_PROFILE) may not work correctly"
  fi
}

# ---- Substitute env vars in a file (portable, no envsubst needed) ----
subst_vars() {
  local content
  content="$(cat "$1")"
  content="${content//\$AWS_PROFILE/${AWS_PROFILE:-}}"
  echo "$content"
}

# ---- Install MCP servers ----
install_mcp() {
  echo ""
  load_env

  # Claude: merge mcpServers into settings.json
  if [[ -d "$HOME/.claude" ]]; then
    if ! command -v jq >/dev/null 2>&1; then
      error "jq is required for Claude MCP setup — install it and re-run:"
      error "  Linux: sudo apt install jq | macOS: brew install jq"
    else
      local mcp_json
      mcp_json="$(subst_vars "$MCP_DIR/claude.json")"

      if [[ -f "$CLAUDE_SETTINGS" ]]; then
        local merged
        merged="$(jq -s '.[0] * .[1]' "$CLAUDE_SETTINGS" <(echo "$mcp_json"))"
        echo "$merged" > "$CLAUDE_SETTINGS"
      else
        echo "$mcp_json" > "$CLAUDE_SETTINGS"
      fi
      info "MCP servers → $CLAUDE_SETTINGS"
    fi
  else
    warn "Skipping Claude MCP ($HOME/.claude not found)"
  fi

  # Codex: append MCP blocks to config.toml
  if [[ -d "$CODEX_DIR" ]]; then
    local mcp_toml
    mcp_toml="$(subst_vars "$MCP_DIR/codex.toml")"

    if [[ -f "$CODEX_CONFIG" ]] && grep -q "mcp_servers.awslabs-aws-diagram" "$CODEX_CONFIG" 2>/dev/null; then
      info "MCP servers already in $CODEX_CONFIG (skipping)"
    else
      {
        echo ""
        echo "# --- oxStack MCP servers ---"
        echo "$mcp_toml"
      } >> "$CODEX_CONFIG"
      info "MCP servers → $CODEX_CONFIG"
    fi
  else
    warn "Skipping Codex MCP ($CODEX_DIR not found)"
  fi
}

# ---- UNINSTALL ----
do_uninstall() {
  echo "Uninstalling oxStack..."
  echo ""

  # Remove skill symlinks
  for skill_dir in "$SKILLS_DIR"/*/; do
    [[ -d "$skill_dir" ]] || continue
    local name
    name="$(basename "$skill_dir")"

    if remove_our_link "$CLAUDE_SKILLS/$name"; then
      info "Removed $CLAUDE_SKILLS/$name"
    fi
    if remove_our_link "$AGENTS_SKILLS/$name"; then
      info "Removed $AGENTS_SKILLS/$name"
    fi
  done

  # Remove agent symlinks
  for agent_file in "$AGENTS_DIR"/*.md; do
    [[ -f "$agent_file" ]] || continue
    local name
    name="$(basename "$agent_file")"

    if remove_our_link "$CLAUDE_AGENTS/$name"; then
      info "Removed $CLAUDE_AGENTS/$name"
    fi
  done

  # Remove generated AGENTS.md files (only if they contain our header)
  for agents_md in "$CODEX_DIR/AGENTS.md" "$OPENCODE_DIR/AGENTS.md"; do
    if [[ -f "$agents_md" ]] && head -1 "$agents_md" | grep -q "Generated by oxStack"; then
      rm "$agents_md"
      info "Removed generated $agents_md"
    fi
  done

  # Remove MCP servers from Claude settings.json
  if [[ -f "$CLAUDE_SETTINGS" ]] && command -v jq >/dev/null 2>&1; then
    if jq -e '.mcpServers' "$CLAUDE_SETTINGS" >/dev/null 2>&1; then
      local cleaned
      cleaned="$(jq 'del(.mcpServers)' "$CLAUDE_SETTINGS")"
      echo "$cleaned" > "$CLAUDE_SETTINGS"
      info "Removed MCP servers from $CLAUDE_SETTINGS"
    fi
  fi

  # Remove oxStack MCP block from Codex config.toml
  if [[ -f "$CODEX_CONFIG" ]] && grep -q "oxStack MCP servers" "$CODEX_CONFIG" 2>/dev/null; then
    local tmp
    tmp="$(sed '/^# --- oxStack MCP servers ---$/,$d' "$CODEX_CONFIG")"
    echo "$tmp" > "$CODEX_CONFIG"
    info "Removed MCP servers from $CODEX_CONFIG"
  fi

  echo ""
  info "Done. All oxStack links, generated files, and MCP servers removed."
}

# ---- Main ----
case "${1:-}" in
  --uninstall|-u)
    do_uninstall
    ;;
  --help|-h)
    echo "Usage: $0 [--uninstall]"
    echo ""
    echo "  (no args)     Install skills, agents, and guidelines"
    echo "  --uninstall   Remove all symlinks and generated files"
    ;;
  "")
    do_install
    ;;
  *)
    error "Unknown option: $1"
    echo "Usage: $0 [--uninstall]"
    exit 1
    ;;
esac
