#!/usr/bin/env bash
set -euo pipefail

# =========================
# oxStack Install Script
# Links skills, agents, and guidelines to AI tool config directories.
# =========================

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
SKILLS_DIR="$SCRIPT_DIR/skills"
AGENTS_DIR="$SCRIPT_DIR/agents"
GUIDELINES_DIR="$SCRIPT_DIR/guidelines"

CLAUDE_SKILLS="$HOME/.claude/skills"
AGENTS_SKILLS="$HOME/.agents/skills"
CLAUDE_AGENTS="$HOME/.claude/agents"
CODEX_DIR="$HOME/.codex"
OPENCODE_DIR="$HOME/.opencode"

GENERATED_HEADER="<!-- Generated by oxStack/install.sh — edit files in the oxStack repo instead -->"

# ---- Colors ----
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
RED='\033[0;31m'
NC='\033[0m'

info()  { echo -e "${GREEN}+${NC} $1"; }
warn()  { echo -e "${YELLOW}!${NC} $1"; }
error() { echo -e "${RED}x${NC} $1"; }

# ---- Backup a real file/dir before replacing ----
backup_if_real() {
  local target="$1"
  if [[ -e "$target" && ! -L "$target" ]]; then
    local bak="${target}.bak"
    warn "Backing up $target → $bak"
    mv "$target" "$bak"
  fi
}

# ---- Remove a symlink only if it points to our repo ----
remove_our_link() {
  local target="$1"
  if [[ -L "$target" ]]; then
    local link_target
    link_target="$(readlink -f "$target" 2>/dev/null || readlink "$target")"
    if [[ "$link_target" == "$SCRIPT_DIR"* ]]; then
      rm "$target"
      return 0
    fi
  fi
  return 1
}

# ---- INSTALL ----
do_install() {
  echo "Installing oxStack..."
  echo ""

  # --- Skills → ~/.claude/skills/ and ~/.agents/skills/ ---
  mkdir -p "$CLAUDE_SKILLS" "$AGENTS_SKILLS"

  for skill_dir in "$SKILLS_DIR"/*/; do
    [[ -d "$skill_dir" ]] || continue
    local name
    name="$(basename "$skill_dir")"

    # Claude skills target
    local claude_target="$CLAUDE_SKILLS/$name"
    if [[ -L "$claude_target" ]]; then
      rm "$claude_target"
    else
      backup_if_real "$claude_target"
    fi
    ln -sfn "$skill_dir" "$claude_target"
    info "Skill $name → $claude_target"

    # Agents skills target
    local agents_target="$AGENTS_SKILLS/$name"
    if [[ -L "$agents_target" ]]; then
      rm "$agents_target"
    else
      backup_if_real "$agents_target"
    fi
    ln -sfn "$skill_dir" "$agents_target"
    info "Skill $name → $agents_target"
  done

  echo ""

  # --- Agents → ~/.claude/agents/ ---
  mkdir -p "$CLAUDE_AGENTS"

  for agent_file in "$AGENTS_DIR"/*.md; do
    [[ -f "$agent_file" ]] || continue
    local name
    name="$(basename "$agent_file")"

    local target="$CLAUDE_AGENTS/$name"
    if [[ -L "$target" ]]; then
      rm "$target"
    else
      backup_if_real "$target"
    fi
    ln -sf "$agent_file" "$target"
    info "Agent $name → $target"
  done

  echo ""

  # --- Guidelines → Codex AGENTS.md ---
  if [[ -d "$CODEX_DIR" ]]; then
    local codex_agents="$CODEX_DIR/AGENTS.md"
    backup_if_real "$codex_agents"
    {
      echo "$GENERATED_HEADER"
      echo ""
      cat "$GUIDELINES_DIR/base-guidelines.md"
      echo ""
      cat "$GUIDELINES_DIR/agent-appendix.md"
    } > "$codex_agents"
    info "Generated $codex_agents"
  else
    warn "Skipping Codex ($CODEX_DIR not found)"
  fi

  # --- Guidelines → OpenCode AGENTS.md ---
  if [[ -d "$OPENCODE_DIR" ]]; then
    local opencode_agents="$OPENCODE_DIR/AGENTS.md"
    backup_if_real "$opencode_agents"
    {
      echo "$GENERATED_HEADER"
      echo ""
      cat "$GUIDELINES_DIR/base-guidelines.md"
      echo ""
      cat "$GUIDELINES_DIR/opencode-extra.md"
      echo ""
      cat "$GUIDELINES_DIR/agent-appendix.md"
    } > "$opencode_agents"
    info "Generated $opencode_agents"
  else
    warn "Skipping OpenCode ($OPENCODE_DIR not found)"
  fi

  echo ""
  info "Done. All skills, agents, and guidelines installed."
}

# ---- UNINSTALL ----
do_uninstall() {
  echo "Uninstalling oxStack..."
  echo ""

  # Remove skill symlinks
  for skill_dir in "$SKILLS_DIR"/*/; do
    [[ -d "$skill_dir" ]] || continue
    local name
    name="$(basename "$skill_dir")"

    if remove_our_link "$CLAUDE_SKILLS/$name"; then
      info "Removed $CLAUDE_SKILLS/$name"
    fi
    if remove_our_link "$AGENTS_SKILLS/$name"; then
      info "Removed $AGENTS_SKILLS/$name"
    fi
  done

  # Remove agent symlinks
  for agent_file in "$AGENTS_DIR"/*.md; do
    [[ -f "$agent_file" ]] || continue
    local name
    name="$(basename "$agent_file")"

    if remove_our_link "$CLAUDE_AGENTS/$name"; then
      info "Removed $CLAUDE_AGENTS/$name"
    fi
  done

  # Remove generated AGENTS.md files (only if they contain our header)
  for agents_md in "$CODEX_DIR/AGENTS.md" "$OPENCODE_DIR/AGENTS.md"; do
    if [[ -f "$agents_md" ]] && head -1 "$agents_md" | grep -q "Generated by oxStack"; then
      rm "$agents_md"
      info "Removed generated $agents_md"
    fi
  done

  echo ""
  info "Done. All oxStack links and generated files removed."
}

# ---- Main ----
case "${1:-}" in
  --uninstall|-u)
    do_uninstall
    ;;
  --help|-h)
    echo "Usage: $0 [--uninstall]"
    echo ""
    echo "  (no args)     Install skills, agents, and guidelines"
    echo "  --uninstall   Remove all symlinks and generated files"
    ;;
  "")
    do_install
    ;;
  *)
    error "Unknown option: $1"
    echo "Usage: $0 [--uninstall]"
    exit 1
    ;;
esac
