package main

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

const generatedHeader = "<!-- Generated by oxStack installer — edit files in the oxStack repo instead -->"

// Third-party skills: "repo --skill name"
var thirdPartySkills = []struct{ args, name string }{
	{"vercel-labs/agent-browser --skill agent-browser", "agent-browser"},
	{"vercel-labs/find-skills --skill find-skills", "find-skills"},
	{"AdeelMufti/addyo-skill-accessibility --skill accessibility", "accessibility"},
	{"AdeelMufti/addyo-skill-best-practices --skill best-practices", "best-practices"},
	{"AdeelMufti/addyo-skill-core-web-vitals --skill core-web-vitals", "core-web-vitals"},
	{"AdeelMufti/addyo-skill-performance --skill performance", "performance"},
	{"AdeelMufti/addyo-skill-seo --skill seo", "seo"},
	{"AdeelMufti/addyo-skill-web-quality-audit --skill web-quality-audit", "web-quality-audit"},
	{"mattpocock/tdd --skill tdd", "tdd"},
	{"ast-grep/agent-skill --skill ast-grep", "ast-grep"},
}

// Skills that gstack installs but we replace with agent-browser versions.
var browserDependentSkills = []string{"qa", "browse", "design-review", "qa-design-review"}

func cmdInstall() {
	fmt.Println("Installing oxStack...")
	fmt.Println()

	root := repoRoot()

	// --- Step 1: Symlink skills ---
	installSkillSymlinks(root)

	// --- Step 2: Symlink agents ---
	installAgentSymlinks(root)

	// --- Step 3: Generate AGENTS.md ---
	installGuidelines(root)

	// --- Step 4: MCP servers ---
	installMCP(root)

	// --- Step 5: Clone/pull gstack ---
	installGstack()

	// --- Step 6: Install agent-browser ---
	installAgentBrowser()

	// --- Step 7: Install third-party skills ---
	installThirdPartySkills()

	// --- Step 8: Copy -byOx skills ---
	installByOxSkills(root)

	// --- Step 9: Remove browser-dependent symlinks ---
	removeBrowserSymlinks()

	// --- Step 10: Symlink CLAUDE.md ---
	installClaudeMd(root)

	fmt.Println()
	infof("Done. All skills, agents, guidelines, CLAUDE.md, and MCP servers installed.")
	printPostInstallSummary()
}

func installSkillSymlinks(root string) {
	skillsSrc := filepath.Join(root, "skills")
	claudeSkills := claudeSkillsDir()
	agentsSkills := agentsSkillsDir()

	os.MkdirAll(claudeSkills, 0o755)
	os.MkdirAll(agentsSkills, 0o755)

	entries, err := os.ReadDir(skillsSrc)
	if err != nil {
		warnf("Could not read skills directory: %v", err)
		return
	}

	for _, e := range entries {
		if !e.IsDir() {
			continue
		}
		name := e.Name()
		src := filepath.Join(skillsSrc, name)

		dst := filepath.Join(claudeSkills, name)
		if err := symlink(src, dst); err != nil {
			errorf("Skill %s → %s: %v", name, dst, err)
		} else {
			infof("Skill %s → %s", name, dst)
		}

		dst = filepath.Join(agentsSkills, name)
		if err := symlink(src, dst); err != nil {
			errorf("Skill %s → %s: %v", name, dst, err)
		} else {
			infof("Skill %s → %s", name, dst)
		}
	}
	fmt.Println()
}

func installAgentSymlinks(root string) {
	agentsSrc := filepath.Join(root, "agents")
	claudeAgents := claudeAgentsDir()

	os.MkdirAll(claudeAgents, 0o755)

	entries, err := os.ReadDir(agentsSrc)
	if err != nil {
		warnf("Could not read agents directory: %v", err)
		return
	}

	for _, e := range entries {
		if e.IsDir() || !strings.HasSuffix(e.Name(), ".md") {
			continue
		}
		name := e.Name()
		src := filepath.Join(agentsSrc, name)
		dst := filepath.Join(claudeAgents, name)

		if err := symlink(src, dst); err != nil {
			errorf("Agent %s → %s: %v", name, dst, err)
		} else {
			infof("Agent %s → %s", name, dst)
		}
	}
	fmt.Println()
}

func installGuidelines(root string) {
	guidelinesDir := filepath.Join(root, "guidelines")

	baseGuidelines, err := os.ReadFile(filepath.Join(guidelinesDir, "base-guidelines.md"))
	if err != nil {
		warnf("Could not read base-guidelines.md: %v", err)
		return
	}
	agentAppendix, err := os.ReadFile(filepath.Join(guidelinesDir, "agent-appendix.md"))
	if err != nil {
		warnf("Could not read agent-appendix.md: %v", err)
		return
	}

	// Codex AGENTS.md
	codex := codexDir()
	if dirExists(codex) {
		content := generatedHeader + "\n\n" + string(baseGuidelines) + "\n" + string(agentAppendix)
		path := filepath.Join(codex, "AGENTS.md")
		if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
			errorf("Could not write %s: %v", path, err)
		} else {
			infof("Generated %s", path)
		}
	} else {
		warnf("Skipping Codex (%s not found)", codex)
	}

	// OpenCode AGENTS.md
	opencode := opencodeDir()
	if dirExists(opencode) {
		opencodeExtra, _ := os.ReadFile(filepath.Join(guidelinesDir, "opencode-extra.md"))
		content := generatedHeader + "\n\n" + string(baseGuidelines) + "\n" + string(opencodeExtra) + "\n" + string(agentAppendix)
		path := filepath.Join(opencode, "AGENTS.md")
		if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
			errorf("Could not write %s: %v", path, err)
		} else {
			infof("Generated %s", path)
		}
	} else {
		warnf("Skipping OpenCode (%s not found)", opencode)
	}
}

func installMCP(root string) {
	fmt.Println()

	// Load .env for variable substitution
	envVars := loadEnvFile(filepath.Join(root, ".env"))

	claudeDir := filepath.Join(homeDir(), ".claude")
	if !dirExists(claudeDir) {
		warnf("Skipping Claude MCP (%s not found)", claudeDir)
		return
	}

	// Read our MCP config
	mcpPath := filepath.Join(root, "mcp", "claude.json")
	mcpData, err := os.ReadFile(mcpPath)
	if err != nil {
		warnf("Could not read %s: %v", mcpPath, err)
		return
	}

	// Substitute env vars
	mcpStr := string(mcpData)
	for k, v := range envVars {
		mcpStr = strings.ReplaceAll(mcpStr, "$"+k, v)
	}

	// Parse our MCP JSON
	var ourConfig map[string]any
	if err := json.Unmarshal([]byte(mcpStr), &ourConfig); err != nil {
		errorf("Invalid JSON in %s: %v", mcpPath, err)
		return
	}

	// Read existing settings.json (or start fresh)
	settingsPath := claudeSettingsPath()
	var existing map[string]any

	if data, err := os.ReadFile(settingsPath); err == nil {
		if err := json.Unmarshal(data, &existing); err != nil {
			warnf("Could not parse %s, will overwrite: %v", settingsPath, err)
			existing = nil
		}
	}

	// Merge: our config into existing
	if existing == nil {
		existing = ourConfig
	} else {
		mergeJSON(existing, ourConfig)
	}

	// Write back
	out, err := json.MarshalIndent(existing, "", "  ")
	if err != nil {
		errorf("Could not marshal settings: %v", err)
		return
	}
	if err := os.WriteFile(settingsPath, append(out, '\n'), 0o644); err != nil {
		errorf("Could not write %s: %v", settingsPath, err)
		return
	}
	infof("MCP servers → %s", settingsPath)

	// Codex config.toml
	installCodexMCP(root, envVars)
}

func installCodexMCP(root string, envVars map[string]string) {
	codex := codexDir()
	if !dirExists(codex) {
		warnf("Skipping Codex MCP (%s not found)", codex)
		return
	}

	codexConfig := codexConfigPath()
	tomlPath := filepath.Join(root, "mcp", "codex.toml")
	tomlData, err := os.ReadFile(tomlPath)
	if err != nil {
		warnf("Could not read %s: %v", tomlPath, err)
		return
	}

	tomlStr := string(tomlData)
	for k, v := range envVars {
		tomlStr = strings.ReplaceAll(tomlStr, "$"+k, v)
	}

	// Check if already present
	if data, err := os.ReadFile(codexConfig); err == nil {
		if strings.Contains(string(data), "mcp_servers.awslabs-aws-diagram") {
			infof("MCP servers already in %s (skipping)", codexConfig)
			return
		}
	}

	f, err := os.OpenFile(codexConfig, os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0o644)
	if err != nil {
		errorf("Could not open %s: %v", codexConfig, err)
		return
	}
	defer f.Close()

	fmt.Fprintf(f, "\n# --- oxStack MCP servers ---\n%s", tomlStr)
	infof("MCP servers → %s", codexConfig)
}

func installGstack() {
	fmt.Println()
	gstack := gstackDir()

	if dirExists(gstack) {
		warnf("gstack already exists at %s — pulling latest", gstack)
		// Discard local changes to compiled binaries so the pull is never blocked.
		runDir(gstack, "git", "checkout", "--", "bin/")
		if out, err := runDir(gstack, "git", "pull", "--ff-only"); err != nil {
			warnf("Could not pull gstack: %s", strings.TrimSpace(out))
		}
	} else {
		infof("Cloning gstack...")
		if out, err := run("git", "clone", "--depth", "1", "https://github.com/garrytan/gstack.git", gstack); err != nil {
			errorf("Could not clone gstack: %s", strings.TrimSpace(out))
			return
		}
	}
	infof("gstack ready at %s", gstack)
}

func installAgentBrowser() {
	fmt.Println()

	if commandExists("agent-browser") {
		infof("agent-browser already installed")
	} else {
		infof("Installing agent-browser...")
		if out, err := run("npm", "install", "-g", "agent-browser"); err != nil {
			errorf("Could not install agent-browser: %s", strings.TrimSpace(out))
			return
		}
	}

	infof("Setting up browser for agent-browser...")
	if out, err := run("agent-browser", "install", "--with-deps"); err != nil {
		warnf("agent-browser install issue: %s", strings.TrimSpace(out))
	}
}

func installThirdPartySkills() {
	fmt.Println()
	infof("Installing third-party skills...")

	agentsSkills := agentsSkillsDir()
	for _, skill := range thirdPartySkills {
		dir := filepath.Join(agentsSkills, skill.name)
		if dirExists(dir) {
			infof("  Already installed: %s", skill.name)
			continue
		}
		args := append([]string{"skills", "add"}, strings.Fields(skill.args)...)
		if out, err := run("npx", args...); err != nil {
			warnf("  Could not install %s: %s", skill.name, strings.TrimSpace(out))
		} else {
			infof("  Installed: %s", skill.name)
		}
	}
}

func installByOxSkills(root string) {
	fmt.Println()
	skillsDir := claudeSkillsDir()
	gstackAbDir := filepath.Join(root, "gstack-ab", "skills")

	// qa-byOx
	infof("Installing qa-byOx skill...")
	qaByOx := filepath.Join(skillsDir, "qa-byOx")
	os.MkdirAll(filepath.Join(qaByOx, "references"), 0o755)
	copyFile(filepath.Join(gstackAbDir, "qa", "SKILL.md"), filepath.Join(qaByOx, "SKILL.md"))
	refSrc := filepath.Join(gstackAbDir, "qa", "references", "issue-taxonomy.md")
	if fileExists(refSrc) {
		copyFile(refSrc, filepath.Join(qaByOx, "references", "issue-taxonomy.md"))
	}
	tmplSrc := filepath.Join(gstackAbDir, "qa", "templates", "qa-report-template.md")
	if fileExists(tmplSrc) {
		os.MkdirAll(filepath.Join(qaByOx, "templates"), 0o755)
		copyFile(tmplSrc, filepath.Join(qaByOx, "templates", "qa-report-template.md"))
	}
	infof("  Installed: /qa-byOx")

	// design-review-byOx
	infof("Installing design-review-byOx skill...")
	drByOx := filepath.Join(skillsDir, "design-review-byOx")
	os.MkdirAll(drByOx, 0o755)
	copyFile(filepath.Join(gstackAbDir, "design-review", "SKILL.md"), filepath.Join(drByOx, "SKILL.md"))
	infof("  Installed: /design-review-byOx")
}

func installClaudeMd(root string) {
	fmt.Println()
	src := filepath.Join(root, "CLAUDE.md")
	if !fileExists(src) {
		warnf("No CLAUDE.md found in repo root — skipping")
		return
	}
	claudeDir := filepath.Join(homeDir(), ".claude")
	os.MkdirAll(claudeDir, 0o755)
	dst := filepath.Join(claudeDir, "CLAUDE.md")
	if err := symlink(src, dst); err != nil {
		errorf("CLAUDE.md → %s: %v", dst, err)
	} else {
		infof("CLAUDE.md → %s", dst)
	}
}

func removeBrowserSymlinks() {
	fmt.Println()
	infof("Removing gstack browser-dependent skill symlinks...")
	skillsDir := claudeSkillsDir()

	for _, name := range browserDependentSkills {
		target := filepath.Join(skillsDir, name)
		info, err := os.Lstat(target)
		if err != nil {
			continue
		}
		if info.Mode()&os.ModeSymlink != 0 {
			os.Remove(target)
			infof("  Removed: %s (replaced by agent-browser version)", name)
		}
	}
}

func printPostInstallSummary() {
	fmt.Println()
	fmt.Println("  Installed by this script:")
	fmt.Println()
	fmt.Println("    oxStack skills (cross-platform, agent-browser):")
	fmt.Println("      /qa-byOx              — QA testing via agent-browser")
	fmt.Println("      /design-review-byOx   — Design audit via agent-browser")
	fmt.Println()
	fmt.Println("    Third-party skills:")
	fmt.Println("      /agent-browser        — Browser automation (Vercel)")
	fmt.Println("      /find-skills          — Discover installable skills (Vercel)")
	fmt.Println("      /accessibility        — WCAG 2.2 audit (Addy Osmani)")
	fmt.Println("      /best-practices       — Security & code quality (Addy Osmani)")
	fmt.Println("      /core-web-vitals      — LCP/INP/CLS optimization (Addy Osmani)")
	fmt.Println("      /performance          — Page speed optimization (Addy Osmani)")
	fmt.Println("      /seo                  — Search engine optimization (Addy Osmani)")
	fmt.Println("      /web-quality-audit    — Lighthouse audit (Addy Osmani)")
	fmt.Println("      /tdd                  — Test-driven development (Matt Pocock)")
	fmt.Println("      /ast-grep             — AST-based structural code search (ast-grep)")
	fmt.Println()
	fmt.Println("    CLI: oxstack install | oxstack sync | oxstack update | oxstack pull-config")
	fmt.Println()
	fmt.Println("  Run 'oxstack sync' after gstack updates to review changes to forked skills")
}

// --- Helpers ---

// loadEnvFile reads a .env file and returns key=value pairs.
func loadEnvFile(path string) map[string]string {
	vars := make(map[string]string)
	data, err := os.ReadFile(path)
	if err != nil {
		return vars
	}
	for _, line := range strings.Split(string(data), "\n") {
		line = strings.TrimSpace(line)
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		if k, v, ok := strings.Cut(line, "="); ok {
			vars[strings.TrimSpace(k)] = strings.TrimSpace(v)
		}
	}
	return vars
}

// mergeJSON does a shallow merge of src into dst (src values win).
// For nested objects, it recurses.
func mergeJSON(dst, src map[string]any) {
	for k, sv := range src {
		if dv, ok := dst[k]; ok {
			// If both are maps, recurse
			if dm, dok := dv.(map[string]any); dok {
				if sm, sok := sv.(map[string]any); sok {
					mergeJSON(dm, sm)
					continue
				}
			}
		}
		dst[k] = sv
	}
}

func dirExists(path string) bool {
	info, err := os.Stat(path)
	return err == nil && info.IsDir()
}

func fileExists(path string) bool {
	info, err := os.Stat(path)
	return err == nil && !info.IsDir()
}
