package main

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// mcpServerKeys lists the keys we add to settings.json mcpServers.
var mcpServerKeys = []string{
	"awslabs.aws-diagram-mcp-server",
	"awslabs.aws-documentation-mcp-server",
	"awslabs.aws-pricing-mcp-server",
	"awslabs.cfn-mcp-server",
	"serverless",
	"ultracite",
	"powertools",
}

func cmdUninstall() {
	fmt.Printf(bold+"oxstack uninstall"+reset+" — remove all oxStack symlinks, generated files, and MCP servers\n\n")

	root := repoRoot()

	// --- Step 1: Remove skill symlinks ---
	removeSkillSymlinks(root)

	// --- Step 2: Remove agent symlinks ---
	removeAgentSymlinks(root)

	// --- Step 3: Remove generated AGENTS.md files ---
	removeGeneratedGuidelines()

	// --- Step 4: Remove MCP servers from Claude settings.json ---
	removeMCPFromClaude()

	// --- Step 5: Remove MCP block from Codex config.toml ---
	removeMCPFromCodex()

	// --- Step 6: Remove -byOx skills ---
	removeByOxSkills()

	fmt.Println()
	infof("Done. All oxStack links, generated files, and MCP servers removed.")
}

func removeSkillSymlinks(root string) {
	skillsSrc := filepath.Join(root, "skills")
	entries, err := os.ReadDir(skillsSrc)
	if err != nil {
		return
	}

	claudeSkills := claudeSkillsDir()
	agentsSkills := agentsSkillsDir()

	for _, e := range entries {
		if !e.IsDir() {
			continue
		}
		name := e.Name()
		src := filepath.Join(skillsSrc, name)

		if removeOurSymlink(filepath.Join(claudeSkills, name), src) {
			infof("Removed %s/%s", claudeSkills, name)
		}
		if removeOurSymlink(filepath.Join(agentsSkills, name), src) {
			infof("Removed %s/%s", agentsSkills, name)
		}
	}
}

func removeAgentSymlinks(root string) {
	agentsSrc := filepath.Join(root, "agents")
	entries, err := os.ReadDir(agentsSrc)
	if err != nil {
		return
	}

	claudeAgents := claudeAgentsDir()

	for _, e := range entries {
		if e.IsDir() || !strings.HasSuffix(e.Name(), ".md") {
			continue
		}
		name := e.Name()
		src := filepath.Join(agentsSrc, name)

		if removeOurSymlink(filepath.Join(claudeAgents, name), src) {
			infof("Removed %s/%s", claudeAgents, name)
		}
	}
}

// removeOurSymlink removes target only if it's a symlink pointing into src's directory.
func removeOurSymlink(target, src string) bool {
	info, err := os.Lstat(target)
	if err != nil || info.Mode()&os.ModeSymlink == 0 {
		return false
	}

	linkDest, err := filepath.EvalSymlinks(target)
	if err != nil {
		return false
	}

	srcReal, err := filepath.EvalSymlinks(src)
	if err != nil {
		srcReal = src
	}

	if linkDest == srcReal || strings.HasPrefix(linkDest, srcReal+string(filepath.Separator)) {
		os.Remove(target)
		return true
	}
	return false
}

func removeGeneratedGuidelines() {
	for _, path := range []string{
		filepath.Join(codexDir(), "AGENTS.md"),
		filepath.Join(opencodeDir(), "AGENTS.md"),
	} {
		data, err := os.ReadFile(path)
		if err != nil {
			continue
		}
		if strings.Contains(string(data), "Generated by oxStack") {
			os.Remove(path)
			infof("Removed generated %s", path)
		}
	}
}

func removeMCPFromClaude() {
	settingsPath := claudeSettingsPath()
	data, err := os.ReadFile(settingsPath)
	if err != nil {
		return
	}

	var settings map[string]any
	if err := json.Unmarshal(data, &settings); err != nil {
		return
	}

	mcpServers, ok := settings["mcpServers"].(map[string]any)
	if !ok || len(mcpServers) == 0 {
		return
	}

	removed := 0
	for _, key := range mcpServerKeys {
		if _, exists := mcpServers[key]; exists {
			delete(mcpServers, key)
			removed++
		}
	}

	if removed == 0 {
		return
	}

	// Remove mcpServers entirely if empty
	if len(mcpServers) == 0 {
		delete(settings, "mcpServers")
	}

	out, err := json.MarshalIndent(settings, "", "  ")
	if err != nil {
		return
	}
	os.WriteFile(settingsPath, append(out, '\n'), 0o644)
	infof("Removed %d MCP servers from %s", removed, settingsPath)
}

func removeMCPFromCodex() {
	codexConfig := codexConfigPath()
	data, err := os.ReadFile(codexConfig)
	if err != nil {
		return
	}

	content := string(data)
	marker := "# --- oxStack MCP servers ---"
	idx := strings.Index(content, marker)
	if idx < 0 {
		return
	}

	// Remove everything from the marker to the end
	trimmed := strings.TrimRight(content[:idx], "\n") + "\n"
	os.WriteFile(codexConfig, []byte(trimmed), 0o644)
	infof("Removed MCP servers from %s", codexConfig)
}

func removeByOxSkills() {
	skillsDir := claudeSkillsDir()
	for _, name := range []string{"qa-byOx", "design-review-byOx"} {
		dir := filepath.Join(skillsDir, name)
		if dirExists(dir) {
			os.RemoveAll(dir)
			infof("Removed %s", dir)
		}
	}
}
